export const NICE_PAY = {
    CREDIT_CARD_SUCCESS: '3001',
    REAL_TIME_ACCOUNT_TRANSFER_SUCCESS: '4000',
    VIRTUAL_ACCOUNT_SUCCESS: '4100',
    MOBILE_PAY_SUCCESS: 'A000',
    CASH_RECEIPT_SUCCESS: '7001'
}